# Values for kiva-ui Qa deployment
# - refer to /deploy/charts/values.yaml for defaults and commentary

image:
  repository: kiva/ui
  tag: "" # Expected be set by Jenkins
  pullPolicy: Always

deployenv:
  environment: "k8sqa" # injected into deployment template

secretName: kiva-ui

service:
  type: ClusterIP
  port: 8888
  portName: &servicePortName "http"

resources:
  requests:
    cpu: 250m
    memory: 300Mi
  limits:
    cpu: 250m
    memory: 300Mi

replicaCount: 2
minReplicas: 2
maxReplicas: 6

metrics:
  name: cpu
  target:
    type: Utilization
    averageUtilization: 60

ingress:
  host: "ui-qa.dk1.kiva.org"
  spec:
    rules:
      - host: "ui-qa.dk1.kiva.org"
        http:
          paths:
          - backend:
              serviceName: "kiva-ui"
              servicePort: *servicePortName
            path: /
  tls:
    - hosts:
      - ui-qa.dk1.kiva.org
      secretName: "kiva-ui-tls"
  whitelist:
    enabled: true

configmap:
  data:
  - key: DD_TRACE_GLOBAL_TAGS
    value: "env:qa,app:kiva-ui"
  - key: DD_ENV
    value: "qa"
