name: Ui Tests

on:
  push:
    branches:
      - master
      - 'release-*'
  pull_request:
    branches:
      - master
      - 'release-*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: Update NPM to v7
      run: npm install -g npm@latest
    - name: Install dependencies
      run: npm ci
    - name: Run Lint
      run: npm run lint
    - name: Run Unit Tests
      run: npm run unit
    - name: Run e2e Tests
      uses: cypress-io/github-action@v2
      with:
        browser: chrome
        headless: true
        build: npm run build:cypress
        start: npm start -- --mock --config=local
        wait-on: 'http://localhost:8888/ui-site-map'
        command: npm run e2e:headless
    - name: Merge test coverage reports
      run: npm run coverage:merge
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: 'test/coverage/lcov.info'
